### ISSUE TITLE
Modifying GlobalTransform instead of Transform

### ISSUE THREAD

**Issue by SamiPirbay** [RustyStriker/bevy_physimple#1]
Is there a reason why GlobalTransform is modified rather than Transform?

It prevents children from moving alongside their parents

**Comment by RustyStriker** [comment]
It is mainly a choice here... tho i might just misunderstanding how the transform system works in bevy, i just used `GlobalTransform` to see the position relative to world and modified it directly to not overlap the 2 and complicate things(assuming moving the `GlobalTransform` of an entity will affect its children)

**Comment by SamiPirbay** [comment]
It's preventing my child entities to move with their parent; I guess the GlobalTransform of the parent doesn't affect its children. Only its Transform does. Replacing GlobalTransform with Transform in the source code fixes that problem for me.

In the [Bevy cheatbook](https://bevy-cheatbook.github.io/programming/parent-child.html):

> The Transform represents the relative position. You can manipulate it directly.
> The GlobalTransform represents the absolute position. It is managed by bevy internally; do not manipulate it yourself.

Also in the [transforms page](https://bevy-cheatbook.github.io/features/transforms.html)
> GlobalTransform represents the absolute global position in the world. If the entity does not have a parent, then this will have the same value as the Transform. The value of GlobalTransform is calculated/managed internally by Bevy. You should treat it as read-only; do not mutate it.

**Comment by RustyStriker** [comment]
Yeah i have ran some checks now, seems really weird for me and i will replace it in the necessary places, thanks for the clarification

**Comment by RustyStriker** [comment]
it pretty much solves it(tho it will be a while until i actually finish stuff for a next release
